[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

  [plugins.inputs]
    # Add forms support
    functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
